config:
    policy:
        spread-expire-date:
            unit: m #yMdhms
            duration: 10 #0~
        viewable-date:
            unit: d #yMdhms
            duration: 7 #0~

    scheduler:
        spread-to-expire:
            cron: '0 0 0/1 * * *' #1시간마다 실행